### ISSUE TITLE
Turkish Translations

### ISSUE THREAD

**Issue by uguryilmaz** [syncfusion/ej-global#43]
Hi, i made turkish transaltion corrected. it has a lot of mistranslation and spell error. i want to make a pull request but i sont have the permission to make a PR. if you can give permission i will update the turkish translations.

**Comment by mohankumar91** [comment]
Hi uguryilmaz,

Thanks for your help to correct the words in Turkish culture .Could you please provide your changes as pull request and we will ensure and merged it to our repository.

Regards,
Mohankumar R

**Comment by uguryilmaz** [comment]
i am trying to make a pull request but i have following error.

![image](https://user-images.githubusercontent.com/6348819/30544607-bdebc7ba-9c8f-11e7-9848-9d7e9b78544d.png)

**Comment by karthickthangasamy** [comment]
@uguryilmaz We appreciate your effort.

Could you please fork our repo and create pull request.? Since, you doesn't have permissions for our main repo.

Fork GitHub repo, refer [here](https://help.github.com/articles/fork-a-repo/#fork-an-example-repository)
Pull request from forked repo, refer [here](https://help.github.com/articles/creating-a-pull-request-from-a-fork/).

If you are still facing issues with permission, please use this repo invite [link](https://github.com/karthickthangasamy/ej-global/invitations) to directly commit your changes. We will create PR from there once you committed the changes.

Thanks,
Karthick T

**Comment by uguryilmaz** [comment]
i commit the changes that i made to your repo. i will be happy if you can make a PR from there. thanks.

**Comment by karthickthangasamy** [comment]
@uguryilmaz Yes, I have created PR #44 . We will review the changes and do the needful at the earliest.

We once again appreciate your effort.

Thanks,
Karthick T

**Comment by karthickthangasamy** [comment]
@uguryilmaz The PR #44 has been merged. Thanks. 😄
